### ISSUE TITLE
Minor bug in opcua_threadpool

### ISSUE THREAD

**Issue by harsimran15** [OPCFoundation/UA-AnsiC#102]
Hi

There is a minor bug in OpcUa_ThreadPool_ThreadMain() function. The uFreeThreads variable is continuously incremented when the thread is free which causes its value to increase endlessly.

Although, at the moment the variable is not used but it may cause problems in future.

Thank you.

**Comment by bernd-edlinger** [comment]
I think removal of the Thread Pool class would be  better option
because it is completely untested code and the stack does not use it.

Is there anybody using this Thread Pool stuff?

**Comment by bernd-edlinger** [comment]
Fixed.
