### ISSUE TITLE
Support for Reverse Hello Message

### ISSUE THREAD

**Issue by harsimran15** [OPCFoundation/UA-AnsiC#116]
Does the stack supports reverse hello message?
Is it planned to add such support in stack in near future?

**Comment by bernd-edlinger** [comment]
> Does the stack supports reverse hello message?

Currently not.

> Is it planned to add such support in stack in near future?

Yes, But....

**Comment by harsimran15** [comment]
But ?
What ?

**Comment by bernd-edlinger** [comment]
First we will see pub/sub support.
So this is just one of a number of to be implemented v1.04 topics.
