### ISSUE TITLE
Argument a_pType is opcUa_Null

### ISSUE THREAD

**Issue by kieranHay** [OPCFoundation/UA-AnsiC#14]
Using KEPServerEX to get something working with these samples I get in a loop of:
Return Error: Argument a_pType is opcUa_Null!
GotoError: Bad statuscode 0x80AB0000
"(null)" = 0x80AB0000 (BAD).
GotoError: Bad statuscode 0x80AB0000
"(null)" = 0x80AB0000 (BAD).
GotoError: Bad statuscode 0x80AB0000
"(null)" = 0x80AB0000 (BAD).
GotoError: Bad statuscode 0x80AB0000
OpcUa_secureListener_ProcessRequest: Closing channel due error 0x80AB0000
OpcUa_TcpListener_SendErrorMessage: to 127.0.0.1.53374 (socket 007E3D00) with statusCode 0x80AB0000
"(null)" = 0x80AB0000 (BAD).
OpcUa_TcpListener_ReadEventHandler: Process Request returned an error (0x80AB0000)!

At the Kepserver end I'm getting the same error and then its reconnecting, the constant cycle of failure. 

I've been trying to get any of the OPC foundation examples working for the past 2 days now and all of them seem to fail in some way (Including the recent release version). 

I know this is a beta but this version has done the most so far as I've been able to browse the server using kepserver.

Thanks inadvance.

**Comment by bernd-edlinger** [comment]
should be fixed now, thanks for reporting.
