### ISSUE TITLE
Sample Client

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-AnsiC#15]
A sample client demonstrating how to use the APIs should be provided.

**Comment by barnstee** [comment]
This is part of the Publisher pull request.

**Comment by hzexe** [comment]
The same matter for me.

**Comment by barnstee** [comment]
The Publisher is first and foremost a UA Client and checked-in here:
https://github.com/OPCFoundation/UA-AnsiC/tree/prototyping/AnsiCSamplePublisher
You can use it for your client.

**Comment by lingtongyan** [comment]
how to use subscription APIs both on server and client?
