### ISSUE TITLE
Adding node inside simple SERVER

### ISSUE THREAD

**Issue by vittoriotranquillo** [OPCFoundation/UA-AnsiC#16]
Hello.
It's OPC UA (ANSI C stack).What I should do is simply to ensure that the server adds a node to its address space: no Subscription, no security, no browsing. Only one session and add a node (which may also be a simple integer).
On the basis of "ansicservermain.c", could you able to help me or direct me to someone?

Thanks

**Comment by bernd-edlinger** [comment]
I actually can't give any support for the AnsiCSample, but I promise,
I will merge a pull request if someone cares to implement this.
