### ISSUE TITLE
Verify / follow improved rules for multi dimensional arrays (Mantis 2819/2860)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-AnsiC#3]
Additional rule for Variant decoding in UA Part 6:
"If ArrayDimensions are inconsistent with the ArrayLength then the decoder shall stop and raise a Bad_DecodingError"

**Comment by bernd-edlinger** [comment]
improved check that all array dimensions are > 0
avoid possible overflow in computation
