### ISSUE TITLE
Possible null pointer derefence in OpcUa_P_OpenSSL_X509_GetPrivateKey()

### ISSUE THREAD

**Issue by cacamille3** [OPCFoundation/UA-AnsiC#34]
In the function

```
OpcUa_StatusCode OpcUa_P_OpenSSL_X509_GetPrivateKey(
    OpcUa_CryptoProvider*       a_pProvider,
    OpcUa_StringA               a_certificateFileName,
    OpcUa_StringA               a_password,             /* this is optional */
    OpcUa_Key* a_pPrivateKey)
```

if

`PKCS12_parse(pPKCS12Cert, a_password, &pPrivateKey, OpcUa_Null, OpcUa_Null);`

fails then the pPrivateKey might be still NULL which will lead to a null pointer dereference when trying to get the type of Private key just after.

`switch(EVP_PKEY_type(pPrivateKey->type))`

The function PKCS12_parse is actually returning 1 for success and zero if an error occurred, so we could check for the result.

**Comment by bernd-edlinger** [comment]
Yes, even wrong password could trigger a crash here.

The recommended way to load your private keys is using
OpcUa_P_OpenSSL_RSA_LoadPrivateKeyFromFile.

I think it would be best to remove OpcUa_P_OpenSSL_X509_GetPrivateKey
and OpcUa_P_OpenSSL_X509_GetPublicKey in favour of
OpcUa_P_OpenSSL_RSA_LoadPrivateKeyFromFile and
OpcUa_P_OpenSSL_X509_LoadFromFile.
