### ISSUE TITLE
opcua_endpoint_ex.c is missing

### ISSUE THREAD

**Issue by eckes** [OPCFoundation/UA-AnsiC#41]
In version 1.02-336.1, the file `stack/proxystub/serverstub/opcua_endpoint_ex.c` was contained in the sources. Browsing the history of this repo shows me that the file is missing from the beginning.

The rationale for that file was to be able to provide an own de-/encoder which improves performance and saves memory because you could directly deserialize into or serialize from your native data types.

We've used that functionality and now cannot update to 1.03.340 because of that file missing. At least not without putting a huge effort in re-creating all the conversion stuff that we don't need when using `opcua_endpoint_ex.c`.

Please reinclude that file in the distribution.

**Comment by bernd-edlinger** [comment]
We have no test coverage whatsoever on this file, therefore it was discontinued at the time
when the https protocol was introduced, sorry.
But I do not understand why you can't directly use the SecureListener API.

**Comment by eckes** [comment]
The SecureListener API is a good point. Thanks for the hint.
