### ISSUE TITLE
Missing credentials for the ANSI C example server

### ISSUE THREAD

**Issue by Elmi77** [OPCFoundation/UA-AnsiC#44]
What are the login-data for the example server? I found "Softing!" as hard-coded password but no valid user name to be used from within a client.
So what are the login data? Shouldn't there be a short README with them?

**Comment by cacamille3** [comment]
The UserName given in the OpcUa_UserNameIdentityToken structure passed in the first call of ActivateSession's check_useridentitytoken() will be saved as the login username (in the speichere_username() function in ansiservermain)
Only the password is compared with the one hard-coded for the first ActivateSession.

Next ActivateSession will compare the login username and password

The username remain the same until the restart of the Server.

PS: This is only for test, such a mechanism should never be used in production environment
