### ISSUE TITLE
Secure connection can not communicate

### ISSUE THREAD

**Issue by iPuerto** [OPCFoundation/UA-AnsiC#46]
Hello,

I tried secure connetion using AnsiC stack (UA Server). But, the secure connection can not communicate because error occurs at 509 line of 'opcua_p_openssl_rsa.c'. Does this stack support secure connection?

Test tools(Client): UaExpert, OPC-F Sample Client
Security mode: SignAndEncrypt
Security policy: Basic128Rsa15
Authentication Settings: Anonymous

Development tools: Visual Studio 2017
Execution environment: Windows10

**Comment by bernd-edlinger** [comment]
Hi,

the stack itself does support security in principle.
But the sample does only implement a non-secure endpoint.

**Comment by iPuerto** [comment]
Hi,

Thank you for your reply. I understood. I will try.
