### ISSUE TITLE
Possible memory leak in OpcUa_HttpsConnection_Create

### ISSUE THREAD

**Issue by cacamille3** [OPCFoundation/UA-AnsiC#55]
In the `OpcUa_HttpsConnection_Create `function it is possible that the `OpcUa_Timer_Create `function return a Bad statuscode (i.e: `OpcUa_BadResourceUnavailable `if we have reach the max number of Timers).
The returned status code is verified with a `OpcUa_ReturnErrorIfBad(uStatus); `
The `HttpsConnection `is then not deleted

**Comment by bernd-edlinger** [comment]
Also the code path through `OpcUa_GotoErrorIfAllocFailed(pHttpConnection);`
will leak memory because `OpcUa_HttpsConnection_Delete` will do nothing if
if `(*a_ppConnection)->Handle` is null.
