### ISSUE TITLE
Missing Mutex unlock in OpcUa_TcpConnection_AbortSendRequest

### ISSUE THREAD

**Issue by cacamille3** [OPCFoundation/UA-AnsiC#59]
Missing `OPCUA_P_MUTEX_UNLOCK(tcpConnection->ReadMutex);` in `OpcUa_TcpConnection_AbortSendRequest ` after `OpcUa_BeginErrorHandling`;

It could happen with `OpcUa_GotoErrorIfArgumentNull(tcpOutputStream);`

**Comment by bernd-edlinger** [comment]
Fortunately, this is in false conditional code.
Probably it would be best to remove all of that.
