### ISSUE TITLE
why Session abgelaufen

### ISSUE THREAD

**Issue by loujunang** [OPCFoundation/UA-AnsiC#60]
Run demo, client and server connections are often disconnected, and removing the Timer_Callback, if(msec_counter > session_timeout) branch will not disconnect

**Comment by bernd-edlinger** [comment]
Yes, the sessions time out quickly.
I would guess, that is to avoid memory leaks.

**Comment by loujunang** [comment]
@bernd-edlinger Can you provide code for a full subscription demo based on this project

**Comment by bernd-edlinger** [comment]
no, sorry, but I can accept a pull request when someone likes to implement.
