### ISSUE TITLE
Stack does not compile as C++ code

### ISSUE THREAD

**Issue by MarkusErlmann** [OPCFoundation/UA-AnsiC#64]
Currently, the stack cannot be compiled as C++ code because of missing casts after allocations (trigger C2440 with Visual Studio) and comparisons against `== OpcUa_True` (trigger C4805 with Visual Studio).

These missing casts and wrong comparisons are fixed in PR #63

**Comment by bernd-edlinger** [comment]
But this is the ANSI C Stack.

**Comment by MarkusErlmann** [comment]
Yes, of course it is.

But with a *handfull* of trivial changes it can also be compiled as C++ code with stricter type checking which I would consider being a good thing.

For example, it helps you spot errors like this one:
https://github.com/OPCFoundation/UA-AnsiC/pull/63/files#diff-c3842f8a57f7568c0862693fd9902499L671

**Comment by bernd-edlinger** [comment]
Hmm, that is more like a bug-fix and has nothing to do with trivial changes.

**Comment by bernd-edlinger** [comment]
BTW: The warnings on the comparisons against `== OpcUa_True` indicate a problem with
the platform layer you use.
`OpcUa_True` and `OpcUa_False` are by definition the correct values for a `OpcUa_Boolean`.
