### ISSUE TITLE
Missing identifier and browse name for MaxByteStringLength (Mantis 3382)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-AnsiC#7]
In file 'opcua_identifiers.h' define for NodeId missing:
#define OpcUaId_Server_ServerCapabilities_MaxByteStringLength 12911

In file 'opcua_browsenames.h' define for browse name missing:
#define OpcUa_BrowseName_MaxByteStringLength "MaxByteStringLength"

**Comment by bernd-edlinger** [comment]
fixed.
