### ISSUE TITLE
Unused variables depending on build configuration

### ISSUE THREAD

**Issue by MarkusErlmann** [OPCFoundation/UA-AnsiC#70]
- `pChannel` in `OpcUa_Channel_GetUsedServerCertificate` is only needed when `OPCUA_HAVE_HTTPS`  is defined
- `pInternalChannel` in `OpcUa_Channel_Connect` is only needed when `OPCUA_MULTITHREADED` is defined

The needed changes are contained in #69.

**Comment by bernd-edlinger** [comment]
fixed.
