### ISSUE TITLE
Missing identifier for OperationLimits (Mantis 3383)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-AnsiC#8]
In file 'opcua_identifiers.h' define for NodeId missing:
#define OpcUaId_Server_ServerCapabilities_OperationLimits 11704

--> check for and add all missing identifiers added in UA Spec V1.03

**Comment by bernd-edlinger** [comment]
Done: All UA nodeset identifiers have been updated to V1.03.
BUT we still don't have OpcUaId_Server_ServerCapabilities_OperationLimits
nor any node with numeric id 11704.

**Comment by dk2129** [comment]
The ID I listed is wrong.
It is #define OpcUaId_ServerCapabilitiesType_OperationLimits 11551 
and already included in opcua_identifiers.h

Issue can be closed.

**Comment by bernd-edlinger** [comment]
Yes, confirmed.
Thanks.

**Comment by mlangDE** [comment]
The ID 11704 is not wrong. Both IDs are used for different meanings.
ID 11551 is part of the ObjectTypes and 11704 is the related 'real' node in the ServerObject.
See for this Opc.Ua.NodeSet2.Part5.xml:
'real' node:
<UAObject NodeId="i=11704" BrowseName="OperationLimits" ParentNodeId="i=2268">
    <DisplayName>OperationLimits</DisplayName>
    <Description>Defines the limits supported by the server for different operations.</Description>
    <References>
      <Reference ReferenceType="HasProperty">i=11705</Reference>
      <Reference ReferenceType="HasProperty">i=12165</Reference>
      <Reference ReferenceType="HasProperty">i=12166</Reference>
      <Reference ReferenceType="HasProperty">i=11707</Reference>
      <Reference ReferenceType="HasProperty">i=12167</Reference>
      <Reference ReferenceType="HasProperty">i=12168</Reference>
      <Reference ReferenceType="HasProperty">i=11709</Reference>
      <Reference ReferenceType="HasProperty">i=11710</Reference>
      <Reference ReferenceType="HasProperty">i=11711</Reference>
      <Reference ReferenceType="HasProperty">i=11712</Reference>
      <Reference ReferenceType="HasProperty">i=11713</Reference>
      <Reference ReferenceType="HasProperty">i=11714</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=11564</Reference>
      <Reference ReferenceType="HasComponent" IsForward="false">i=2268</Reference>
    </References>
  </UAObject>

part of ObjectType:
<UAObject NodeId="i=11551" BrowseName="OperationLimits" ParentNodeId="i=2013">
    <DisplayName>OperationLimits</DisplayName>
    <Description>Defines the limits supported by the server for different operations.</Description>
    <References>
      <Reference ReferenceType="HasTypeDefinition">i=11564</Reference>
      <Reference ReferenceType="HasModellingRule">i=80</Reference>
      <Reference ReferenceType="HasComponent" IsForward="false">i=2013</Reference>
    </References>
  </UAObject>


So both ID's are specified and should be available within the file opcua_identifiers.h.
Furthermore exactly these ID are used in the SampleApplications from the OPC Foundation.

Regards,
Martin

**Comment by bernd-edlinger** [comment]
If 11704 is still missing, then you should open a UA-Nodeset issue instead.
