### ISSUE TITLE
OpcUa_ProxyStub_g_PlatformLayerCalltable was nullptr when working with string

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [OPCFoundation/UA-AnsiC#85]
Hello,
While doing the following

`OpcUa_String endpointUrl;
uStatus = OpcUa_String_Initialize(&endpointUrl);
uStatus = OpcUa_String_AttachToString("TEST", OPCUA_STRINGLENZEROTERMINATED, 0, OpcUa_True, OpcUa_True, &endpointUrl);`

I get the error in the subject while doing the MEMORY allocation (OpcUa_Memory_Alloc).
Would you be able to help?
Thanks!

**Comment by bernd-edlinger** [comment]
You need to call OpcUa_ProxyStub_Initialize and  OpcUa_ProxyStub_Initialize
first.

**Comment by mirkocomparetti-synesis** [comment]
Thanks, now it does not complain.
Would you be able to explain why I need to do this to write in a string?
Thanks again!
