### ISSUE TITLE
OpcUa_String_AttachToString Redundant Assign

### ISSUE THREAD

**Issue by MikeGranby** [OPCFoundation/UA-AnsiC#87]
Last line before return:

a_pNewString = (OpcUa_String*)pStringInt;

But a_pNewString is a parameter, so we assign back to it?

**Comment by bernd-edlinger** [comment]
yes, that should be removed.  Thanks!

**Comment by MikeGranby** [comment]
I'm not quite clear what the purpose of pStringInt is at all, since it just holds the same value as a_pNewString and is never changed. I'm assuming it's a relic of some older code?
