### ISSUE TITLE
OpcUa_GetCode and OpcUa_GetFlags are broken after 334 RC (Mantis 3424)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-AnsiC#9]
In file opcua_errorhandling.h there are macros to deal with status codes.

Up to 334 Beta, it had:

/\* get severity and sub code portion of a status code. */
# define OpcUa_GetCode(xCode) (((xCode) & 0xFFFF0000))

/\* get severity and sub code portion of a status code. */
# define OpcUa_GetFlags(xCode) (((xCode) & 0xFFFF0000))

Then on 334 RC it was changed to:

/\* bit masks for the status code fields defined in part 4 */
# define OpcUa_StatusCode_Mask_Severity 0xC0000000
# define OpcUa_StatusCode_Mask_SubCode 0x0FFF0000
# define OpcUa_StatusCode_Mask_StructureChanged OpcUa_StatusCode_StructureChanged
# define OpcUa_StatusCode_Mask_SemanticsChanged OpcUa_StatusCode_SemanticsChanged
# define OpcUa_StatusCode_Mask_InfoType 0x00000C00
# define OpcUa_StatusCode_Mask_InfoBits 0x000003FF
# define OpcUa_StatusCode_Mask_Reserved 0x30003000

[...]

/\* get severity and sub code portion of a status code. */
# define OpcUa_GetCode(xCode) (((xCode) & (OpcUa_StatusCode_Mask_Severity & OpcUa_StatusCode_Mask_SubCode)))

/\* get structure and semantics flags portion of a status code. */
# define OpcUa_GetFlags(xCode) (((xCode) & (OpcUa_StatusCode_Mask_StructureChanged & OpcUa_StatusCode_Mask_SemanticsChanged)))

What is obviously wrong. The diffrent masks should be combined by OR (|), not by AND (&).

---

The fixed code should be:

/\* get severity and sub code portion of a status code. */
# define OpcUa_GetCode(xCode) (((xCode) & (OpcUa_StatusCode_Mask_Severity | OpcUa_StatusCode_Mask_SubCode)))

/\* get structure and semantics flags portion of a status code. */
# define OpcUa_GetFlags(xCode) (((xCode) & (OpcUa_StatusCode_Mask_StructureChanged | OpcUa_StatusCode_Mask_SemanticsChanged)))

Also notice this can be assured to be correct/working by a simple static assertation.

**Comment by bernd-edlinger** [comment]
I don't see what "OpcUa_StatusCode_StructureChanged" and "OpcUa_StatusCode_SemanticsChanged"
might have been defined to.  So I doubt this change request still applies.
