### ISSUE TITLE
Memory allocation not checked

### ISSUE THREAD

**Issue by cacamille3** [OPCFoundation/UA-AnsiC#91]
In some functions there is call to a memory allocation function not followed by a check to know if it was successful or not.

With OpcUa_P_Memory_Alloc :
_Stack\platforms\win32\opcua_p_win32_pki.c_ - `OpcUa_P_Win32_MultiByteToWideChar` - line 112
_Stack\platforms\win32\opcua_p_win32_pki.c_ - `OpcUa_P_Win32_PKI_LoadCertificate` - line 510

With OpcUa_Alloc :
_Stack\platforms\win32\opcua_p_thread.c_ - `OpcUa_P_Thread_Start `(with OPCUA_USE_POSIX defined) - line 177
_Stack\transport\https\opcua_httpsconnection.c_ - `OpcUa_HttpsConnection_AddStreamToSendQueue ` - line 972

**Comment by bernd-edlinger** [comment]
Yeah, thanks for reporting!

No surprise opcua_p_win32_pki.c got _very_ little testing.

I wanted to remove the ifdef OPCUA_USE_POSIX code blocks all the time but did not come to it.
It's not worth fixing that IMO, better delete that stuff, I can do that.

The OpcUa_HttpsConnection_AddStreamToSendQueue is more a readability mess.
If you look closely the loop iterates a second time and terminates after
`uStatus = OpcUa_BadOutOfMemory`.  But no doubt that code deserves to be rewritten.

**Comment by cacamille3** [comment]
Yes, true for the last one. I missed it but it should actually be Ok

**Comment by bernd-edlinger** [comment]
Fixed.
